### ISSUE TITLE
COPYEDIT: the PARTNER page should be changed to reflect the STEWARD PAGE

### ISSUE THREAD

**Issue by carolinewoolard** [dissentertainer/nycreic-wp#3]
http://staging.nycreic.com/partner/
should have the copy from http://nycreic.com/stewards/
@dissentertainer @blerchin not sure why I can't assign this to you or label it, so I'm doing it this way

**Comment by dissentertainer** [comment]
Caroline, can you make copy edits on the Google doc? It's much easier for me to work from a single source.

**Comment by carolinewoolard** [comment]
Sorry, I thought this would be more clear, as it's specific to each section... I don't see where I would put it in the google doc. Can you call/text me to explain? Or write it here?

**Comment by dissentertainer** [comment]
In the Google doc just paste the content from the steward page into the
"partner" page in the exact location you want it to appear and remove any
other copy that already exists. If you want the page to be renamed stewards
please make that edit there. Github is really for code so I would prefer it
if copy edits were made elsewhere for clarity.

**Comment by carolinewoolard** [comment]
Ah, I understand. I haven't used GitHub this way, but am sorry to do it wrong for you! I will add copy now, but I'm confused about why it's not possible for me to just copy and paste into WordPress itself. We need this to be editable in the future... maybe we can chat in the gDoc

**Comment by dissentertainer** [comment]
You can definitely edit in Wordpress going forward. I just want to get everything set up in the staging database first so that we can copy that over to production rapidly and deploy all the changes simultaneously. If you prefer to make your edits in Wordpress directly, you can log in with your normal credentials at http://staging.nycreic.com/so-admin. To edit the text overlaid on the images just edit the primary and secondary headings in the custom metadata section at the bottom of the screen where you edit the page.  

- Max
